# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d2dd6d639e0120ebd68b5de053b84713a5fc3373bfa8ae763b7d40f5736ea71f093a14874fc86b4d3f8ac91ae992ad2fc8f56801625179a667a01d23f96a5ccb

test:
  secret_key_base: 98f56531618fe9f6c94ff15df2d102a8d2a4a3e17e80757dcb069bb040a2c647ee2be6aa5d91ba084d8409f1f36da0ac3f3e4e359d9b8cf648d3473607de2a9a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
